feat(mise-global,usage): make cleanup optional through a flag
Remove `set -u`, else shell var `usage_clean` causes error when
`--clean` not passed, because the var becomes unbounded.

diff --git a/home/private_dot_config/mise/tasks/os/executable_update.tmpl b/home/private_dot_config/mise/tasks/os/executable_update.tmpl
--- a/home/private_dot_config/mise/tasks/os/executable_update.tmpl
+++ b/home/private_dot_config/mise/tasks/os/executable_update.tmpl
@@ -1,28 +1,57 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #MISE description="Update system packages"
 #MISE alias="distro:update"
+#USAGE flag "--clean" help="Clean up after update"
 
-set -eu
+set -e
 
 {{ if eq .chezmoi.os "darwin" -}}
-brew update && brew upgrade && brew cleanup
+brew update 
+brew upgrade 
+
+if [ "$usage_clean" = "true" ]; then
+  brew cleanup
+fi
 
 {{- else if eq .chezmoi.os "linux" -}}
 
 {{ if eq .chezmoi.osRelease.id "ubuntu" -}}
-sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
+sudo apt update
+sudo apt upgrade -y
+
+if [ "$usage_clean" = "true" ]; then
+  sudo apt autoremove -y
+fi
 
 {{ else if eq .chezmoi.osRelease.id "debian" -}}
-sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
+sudo apt update
+sudo apt upgrade -y
+
+if [ "$usage_clean" = "true" ]; then
+  sudo apt autoremove -y
+fi
 
 {{ else if eq .chezmoi.osRelease.id "fedora" -}}
-sudo dnf update -y && sudo dnf autoremove -y
+sudo dnf update -y
+
+if [ "$usage_clean" = "true" ]; then
+  sudo dnf autoremove -y
+fi
 
 {{ else if eq .chezmoi.osRelease.id "centos" -}}
-sudo dnf update -y && sudo dnf autoremove -y
+sudo dnf update -y
+
+if [ "$usage_clean" = "true" ]; then
+  sudo dnf autoremove -y
+fi
 
 {{ else if eq .chezmoi.osRelease.id "arch" -}}
 sudo pacman -Syu --noconfirm
+
+if [ "$usage_clean" = "true" ]; then
+  sudo pacman -Rns $(pacman -Qdtq) --noconfirm 2>/dev/null
+  sudo pacman -Sc --noconfirm
+fi
 
 {{ else -}}
 echo "[dotfiles] Unknown Linux distribution: {{ .chezmoi.osRelease.id }}"
